version: '3.8'

services:

  order-service:
    build:
      context: ./micr-kfk-order-service
      dockerfile: Dockerfile
    ports:
      - "8088:8088"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/micro_order_service
      SPRING_DATASOURCE_USERNAME: springuser
      SPRING_DATASOURCE_PASSWORD: your_password

  user-service:
    build:
      context: ./micr-kfk-user-service
      dockerfile: Dockerfile
    ports:
      - "8087:8087"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/micro_user_service
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 654321
      
  inventory-service:
    build:
      context: ./micr-kfk-inventory-service
      dockerfile: Dockerfile
    ports:
      - "8089:8089"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://admin:admin123@mongodb:27017
      SPRING_DATA_MONGODB_DATABASE: micro_inventory_service
