version: '3.8'

services:
  mysql:
    image: mysql:8.0.39-oracle
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: micro_order_service
      MYSQL_USER: springuser
      MYSQL_PASSWORD: your_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  postgres:
    image: postgres:12-alpine3.21
    container_name: postgres
    environment:
      POSTGRES_DB: micro_user_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 654321
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    depends_on:
      - mysql
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/micro_order_service
      SPRING_DATASOURCE_USERNAME: springuser
      SPRING_DATASOURCE_PASSWORD: your_password

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/micro_user_service
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 654321

volumes:
  mysql_data:
  postgres_data:
