spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: 654321
    url: jdbc:postgresql://localhost:5433/micro_user_service
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
