server:
  port: 8087
spring:
  application:
    name: micr-kfk-user-service
  datasource:
    driver-class-name: org.postgresql.Driver
    password: 654321
    url: jdbc:postgresql://localhost:5432/micro_user_service
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
